version: '3'

services:
  # db:
  #   platform: linux/x86_64
  #   image: mysql:5.7
  #   container_name: godockerDB
  #   environment:
  #     MYSQL_DATABASE: 'bookstore'
  #     # So you don't have to use root, but you can if you like
  #     MYSQL_USER: 'arsalan'
  #     # You can use whatever password you like
  #     MYSQL_PASSWORD: 'arsalan'
  #     # Password for root access
  #     MYSQL_ROOT_PASSWORD: 'arsalan'
  #   ports:
  #     # <Port exposed> : < MySQL Port running inside container>
  #     - '3306:3306'
  #     # Where our data will be persisted
  #   # volumes:
  #   #   - my-db:/var/lib/mysql
  db:
    platform: linux/x86_64
    image: mysql:5.7
    container_name: godockerDB
    environment:
      MYSQL_USER: docker
      MYSQL_ROOT_PASSWORD: password
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: godocker
    ports:
      - "3306:3306"
  api:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db